"use client";
import { useEffect, useState } from "react";
import { adminFetch } from "../_shell";

type Palace = { name: string; primary: string[]; auxiliary: string[] };
type Settings = { schemaVersion: "1.0"; palaces: Palace[] };
const INITIAL: Settings = { schemaVersion: "1.0", palaces: [
  ["命宮","glabella","eyebrows"],["官祿宮","forehead","glabella,eyebrows,eyes"],["父母宮","forehead","eyebrows,eyes"],["福德宮","eyebrows","glabella"],["遷移宮","forehead","glabella,eyes"],["兄弟宮","eyebrows","cheeks"],["夫妻宮","outerEyeCorners","eyebrows,eyes,nose,glabella"],["子女宮","tearTroughs","chin,eyes,philtrum"],["疾厄宮","nasalRoot","nose,eyes"],["財帛宮","nose","eyebrows,eyes"],["奴僕宮","jaw","mouth,cheeks,chin"],["田宅宮","eyes","jaw,mouth"]
].map(([name, primary, auxiliary]) => ({ name, primary: primary.split(","), auxiliary: auxiliary.split(",") })) };
export default function FaceRulesPage() {
  const [settings,setSettings]=useState<Settings>(INITIAL); const [version,setVersion]=useState("沈師十二宮 v2.0"); const [decidedBy,setDecidedBy]=useState("風羿老師"); const [note,setNote]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  async function load(){ setLoading(true); try { const r=await adminFetch("/api/admin/face-rules"); const d=await r.json(); if(!r.ok)throw new Error(d.error||"讀取失敗"); const base=d.draft||d.published; if(base){setSettings(base.settings);setVersion(base.version_label);setDecidedBy(base.decided_by||"風羿老師");setNote(base.note||"");} if(d.setup_required)setMessage(d.setup_required); } catch(e){setMessage(e instanceof Error?e.message:"讀取失敗");} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);
  async function save(){setSaving(true);try{const r=await adminFetch("/api/admin/face-rules",{method:"POST",body:JSON.stringify({versionLabel:version,decidedBy,note,settings})});const d=await r.json();if(!r.ok)throw new Error(d.error||"儲存失敗");setMessage("草稿已儲存；尚未生效。");await load();}catch(e){setMessage(e instanceof Error?e.message:"儲存失敗");}finally{setSaving(false);}}
  async function publish(){if(!confirm("發布後，新分析會套用此版本並記錄版本號；舊版將封存。確定發布？"))return;setSaving(true);try{const r=await adminFetch("/api/admin/face-rules/publish",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"發布失敗");setMessage("已發布；之後的新面相分析會套用此版本。");await load();}catch(e){setMessage(e instanceof Error?e.message:"發布失敗");}finally{setSaving(false);}}
  if(loading)return <p className="admin-empty">讀取中⋯</p>; return <><h1>面相規則設定</h1><p className="lead">沈師十二宮的主／輔部位對應。安全禁則、健康與敏感推論不可在此修改。</p>{message&&<div className="admin-inline-message">{message}</div>}<div className="admin-form-grid"><label>版本名稱<input value={version} onChange={e=>setVersion(e.target.value)}/></label><label>拍板人<input value={decidedBy} onChange={e=>setDecidedBy(e.target.value)}/></label><label>備註<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>宮位</th><th>主部位</th><th>輔部位</th></tr></thead><tbody>{settings.palaces.map((p,i)=><tr key={p.name}><td>{p.name}</td><td><input value={p.primary.join(",")} onChange={e=>setSettings(s=>({...s,palaces:s.palaces.map((x,j)=>j===i?{...x,primary:e.target.value.split(",").filter(Boolean)}:x)}))}/></td><td><input value={p.auxiliary.join(",")} onChange={e=>setSettings(s=>({...s,palaces:s.palaces.map((x,j)=>j===i?{...x,auxiliary:e.target.value.split(",").filter(Boolean)}:x)}))}/></td></tr>)}</tbody></table></div><p className="muted">可用代碼：forehead、eyebrows、eyes、nose、cheeks、mouth、jaw、ears、glabella、nasalRoot、outerEyeCorners、tearTroughs、philtrum、chin。</p><button className="admin-action-btn" disabled={saving} onClick={()=>void save()}>儲存草稿</button> <button className="admin-action-btn ghost" disabled={saving} onClick={()=>void publish()}>發布規則</button></>;
}
