"use client";

import { FormEvent, useEffect, useState } from "react";
import { adminFetch } from "../_shell";

type Card = { id: string; card_id: string; title: string; category: string; school: string | null; safety_level: string; auto_report: boolean; status: string; source_file: string | null; source_pages: number[]; updated_at: string };
type Revision = { id: string; version: number; change_note: string | null; created_at: string; snapshot: Record<string, unknown> };
const empty = { cardId: "", title: "", category: "十二宮位", school: "沈全榮老師教材", technique: "", observation: "", teacherOriginal: "", editorSummary: "", safetyLevel: "standard", autoReport: false, sourceFile: "", sourcePages: "", status: "draft" };

export default function FaceKnowledgeAdminPage() {
  const [items, setItems] = useState<Card[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [revisions, setRevisions] = useState<Revision[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { setLoading(true); const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); const response = await adminFetch(`/api/admin/face-knowledge?${params}`); const body = await response.json(); if (response.ok) setItems(body.items || []); else setMessage(body.error || "讀取失敗"); setLoading(false); }
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function setField(key: string, value: string | boolean) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const payload = { ...form, sourcePages: form.sourcePages.split(",").map((v) => Number(v.trim())).filter((v) => Number.isInteger(v) && v > 0), school: form.school || null, technique: form.technique || null, teacherOriginal: form.teacherOriginal || null, editorSummary: form.editorSummary || null, sourceFile: form.sourceFile || null }; const response = await adminFetch(editing ? `/api/admin/face-knowledge/${editing}` : "/api/admin/face-knowledge", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "儲存失敗"); return; } setMessage("已儲存"); setForm(empty); setEditing(null); await load(); }
  async function edit(item: Card) { setEditing(item.id); setForm({ ...empty, cardId: item.card_id, title: item.title, category: item.category, school: item.school || "", safetyLevel: item.safety_level, autoReport: item.auto_report, status: item.status, sourceFile: item.source_file || "", sourcePages: (item.source_pages || []).join(",") }); const response = await adminFetch(`/api/admin/face-knowledge/${item.id}/revisions`); const body = await response.json(); setRevisions(response.ok ? body.revisions || [] : []); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function archive(id: string) { if (!window.confirm("封存這張知識卡片？")) return; const response = await adminFetch(`/api/admin/face-knowledge/${id}`, { method: "DELETE" }); if (response.ok) await load(); }
  async function importFile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); const response = await adminFetch("/api/admin/face-knowledge/import", { method: "POST", body: JSON.stringify(parsed) }); const body = await response.json(); setMessage(response.ok ? `已匯入 ${body.imported} 張草稿卡片` : body.error || "匯入失敗"); if (response.ok) await load(); } catch { setMessage("匯入檔案格式錯誤"); } event.target.value = ""; }
  return <><h1>面相知識庫</h1><p className="lead">老師文獻、部位觀察與技法卡片。高風險內容預設不進入會員報告。</p><div style={{ display: "flex", gap: 10, margin: "12px 0" }}><a className="admin-action-btn" href="/api/admin/face-knowledge/export">匯出 JSON</a><label className="admin-action-btn ghost">匯入 JSON<input type="file" accept="application/json" onChange={importFile} hidden /></label></div>
    <form onSubmit={submit} style={{ display: "grid", gap: 10, maxWidth: 900, margin: "20px 0" }}><div style={{ display: "flex", gap: 10 }}><input required placeholder="Card ID" value={form.cardId} disabled={!!editing} onChange={(e) => setField("cardId", e.target.value)} /><input required placeholder="標題" value={form.title} onChange={(e) => setField("title", e.target.value)} /><input required placeholder="分類" value={form.category} onChange={(e) => setField("category", e.target.value)} /></div><div style={{ display: "flex", gap: 10 }}><input placeholder="流派" value={form.school} onChange={(e) => setField("school", e.target.value)} /><input placeholder="技法" value={form.technique} onChange={(e) => setField("technique", e.target.value)} /><input placeholder="來源頁碼，例如 2,3" value={form.sourcePages} onChange={(e) => setField("sourcePages", e.target.value)} /></div><input placeholder="來源檔案" value={form.sourceFile} onChange={(e) => setField("sourceFile", e.target.value)} /><textarea required placeholder="可觀察特徵" value={form.observation} onChange={(e) => setField("observation", e.target.value)} rows={3} /><textarea placeholder="老師原文摘要" value={form.teacherOriginal} onChange={(e) => setField("teacherOriginal", e.target.value)} rows={3} /><textarea placeholder="編輯後白話說明" value={form.editorSummary} onChange={(e) => setField("editorSummary", e.target.value)} rows={3} /><div style={{ display: "flex", gap: 10, alignItems: "center" }}><select value={form.safetyLevel} onChange={(e) => setField("safetyLevel", e.target.value)}><option value="standard">standard</option><option value="high">high</option><option value="critical">critical</option></select><select value={form.status} onChange={(e) => setField("status", e.target.value)}><option value="draft">draft</option><option value="teacher_review">teacher_review</option><option value="published">published</option><option value="archived">archived</option></select><label><input type="checkbox" checked={form.autoReport} onChange={(e) => setField("autoReport", e.target.checked)} /> 允許自動引用</label><button className="admin-action-btn" type="submit">{editing ? "更新" : "建立"}</button>{editing && <button type="button" className="admin-action-btn ghost" onClick={() => { setEditing(null); setForm(empty); }}>取消</button>}</div></form>
    {message && <p className="lead">{message}</p>}{editing && revisions.length > 0 && <details style={{ margin: "12px 0 20px" }}><summary>版本紀錄（{revisions.length}）</summary><ul>{revisions.map((revision) => <li key={revision.id}>v{revision.version} · {new Date(revision.created_at).toLocaleString("zh-TW")} · {revision.change_note || "更新"}</li>)}</ul></details>}<div style={{ display: "flex", gap: 10, margin: "20px 0" }}><input placeholder="搜尋標題或 Card ID" value={search} onChange={(e) => setSearch(e.target.value)} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部狀態</option><option value="draft">draft</option><option value="teacher_review">teacher_review</option><option value="published">published</option><option value="archived">archived</option></select><button className="admin-action-btn" onClick={() => void load()}>搜尋</button></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>卡片</th><th>分類</th><th>流派</th><th>風險</th><th>狀態</th><th>更新</th><th>操作</th></tr></thead><tbody>{loading && <tr><td colSpan={7}>讀取中…</td></tr>}{!loading && items.length === 0 && <tr><td colSpan={7}>尚無知識卡片</td></tr>}{items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><div className="muted">{item.card_id}</div></td><td>{item.category}</td><td>{item.school || "—"}</td><td>{item.safety_level}</td><td>{item.status}{item.auto_report ? " · AI" : ""}</td><td>{new Date(item.updated_at).toLocaleDateString("zh-TW")}</td><td><button className="admin-action-btn ghost" onClick={() => edit(item)}>編輯</button> <button className="admin-action-btn ghost" onClick={() => void archive(item.id)}>封存</button></td></tr>)}</tbody></table></div>
  </>;
}
